In [7]:
import numpy as np

n1 = np.array([1,2,3])
print(n1) #넘파이 배열
print([1,2,3]) #파이썬 리스트

display(n1) #넘파이 배열
display([1,2,3]) #파이썬 리스트

[1 2 3]
[1, 2, 3]


array([1, 2, 3])

[1, 2, 3]

In [8]:
n2 = np.array( [[1,2], [3,4]] )
print(n2)
display(n2)

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [9]:
n3 = np.array( [ [[1,2], [3,4]],[[1,2], [3,4]] ])
n3

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [12]:
range(0,5,1)  # 파이썬의 기본 숫자 범위 지정 : 증가치는 정수만 지원.range(0,5,0.5)

range(0, 5)

In [13]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [18]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
%whos  # %기호는 실행환경에서 제공해주는 명령어. 파이썬언어X

Variable   Type       Data/Info
-------------------------------
n1         ndarray    3: 3 elems, type `int32`, 12 bytes
n2         ndarray    2x2: 4 elems, type `int32`, 16 bytes
n3         ndarray    2x2x2: 8 elems, type `int32`, 32 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [23]:
n1.ndim , n1.shape , n1.size

(1, (3,), 3)

In [24]:
n2.ndim , n2.shape, n2.size

(2, (2, 2), 4)

In [28]:
n3.ndim, n3.shape, n3.size

(3, (2, 2, 2), 8)

In [29]:
n2

array([[1, 2],
       [3, 4]])

In [30]:
n2.T

array([[1, 3],
       [2, 4]])

In [33]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arr1.reshape(2,3,-1).reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
arr1.reshape(1,-1) #한개 행이 2차원으로 존재.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [44]:
arr1.reshape(-1) #한개 행이 1차원으로 존재.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
n2 = np.array( [[1,2], [3,4]] ,dtype=float)
n2

array([[1., 2.],
       [3., 4.]])

In [49]:
n11 = np.arange(1,5).reshape(2,2)
n11

array([[1, 2],
       [3, 4]])

In [53]:
n22 = np.arange(5,9).reshape(2,2)
n22

array([[5, 6],
       [7, 8]])

In [52]:
n11+n22

array([[11, 13],
       [15, 17]])

In [54]:
점수 = np.array([1,3,5,9,10])
구분 = np.array( ['fail','fail','fail','pass','pass'] )

In [58]:
내점수 = 8
print(점수 - 내점수)
dists = 점수-내점수
print(dists**2)
dists = dists**2
print(dists)

[-7 -5 -3  1  2]
[49 25  9  1  4]
[49 25  9  1  4]


In [59]:
좌표리스트 = np.array([
    [1,5], # x,y
    [2,10],
    [3,6],
    [4,2],
    [5,3],
    [7,3]
])
구분 = np.array(['fail','fail','fail','pass','pass','pass'])

In [61]:
내좌표 = [5,5]
dists = 좌표리스트 - 내좌표
dists

array([[-4,  0],
       [-3,  5],
       [-2,  1],
       [-1, -3],
       [ 0, -2],
       [ 2, -2]])

In [64]:
dists = dists**2
dists

array([[16,  0],
       [ 9, 25],
       [ 4,  1],
       [ 1,  9],
       [ 0,  4],
       [ 4,  4]], dtype=int32)

In [70]:
dists.sum()
np.sum(dists, axis=1)  # 행(row)단위로 읽어서 열(cal)단위로 계산
print(np.sqrt(np.sum(dists,axis=1)))

[4.         5.83095189 2.23606798 3.16227766 2.         2.82842712]


In [102]:
지점별매출리스트 = np.array([ 
    [1,5,3,3], 
    [2,10,4,4],
    [3,6,7,7],
    [4,2,7,7],
])
구분 = np.array(['경고','경고','경고','승진'])
나의매출 = [2,3,5,5]


In [79]:
arr3 = np.sqrt(((지점별매출리스트 - 나의매출)**2).sum(axis=1))
arr3

array([3.60555128, 7.14142843, 4.24264069, 3.60555128])

In [83]:
print(arr3 < 4)
print(지점별매출리스트[arr3 < 4]) #True인 행들이 출력


[ True False False  True]
[[1 5 3 3]
 [4 2 7 7]]


In [78]:
print(지점별매출리스트[0])  #하나만 쓰면 행 의미.
print(지점별매출리스트[0][0])
print(지점별매출리스트[0,0])

#열만 뽑고 싶을때
print(지점별매출리스트[:,0]) # 인덱싱.

[1 5 3 3]
1
1
[1 2 3 4]


In [99]:
print(지점별매출리스트)
print(지점별매출리스트[ [0,1],[1,1] ])
print(지점별매출리스트[ [1,3],[1,0] ])

[[ 1  5  3  3]
 [ 2 10  4  4]
 [ 3  6  7  7]
 [ 4  2  7  7]]
[ 5 10]
[10  4]


In [97]:
print(지점별매출리스트[ [1,3],[1,0] ])

[10  4]


In [90]:
지점별매출리스트[2:,2:]

array([[7, 7],
       [7, 7]])

In [91]:
np.where(지점별매출리스트%2==0)

(array([1, 1, 1, 1, 2, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 1, 0, 1], dtype=int64))

In [96]:
arr4 = np.where(지점별매출리스트 < 4, "WARNING","Remain")
arr4

array([['WARNING', 'Remain', 'WARNING', 'WARNING'],
       ['WARNING', 'Remain', 'Remain', 'Remain'],
       ['WARNING', 'Remain', 'Remain', 'Remain'],
       ['Remain', 'WARNING', 'Remain', 'Remain']], dtype='<U7')

In [103]:
# 주류,식품,영업매출,개발매출
print(지점별매출리스트)
지점명 = np.array(['A','B','C','D'])

[[ 1  5  3  3]
 [ 2 10  4  4]
 [ 3  6  7  7]
 [ 4  2  7  7]]


In [106]:
print(지점별매출리스트.min(axis=0))
print(지점별매출리스트.min(axis=1))

[1 2 3 3]
[1 2 3 2]


In [109]:
지점명 = list("ABCD")
지점명

['A', 'B', 'C', 'D']

In [110]:
"".join(지점명)

'ABCD'

In [116]:
#지점별매출리스트에서 주류매출이 가장 작은 지점명은?
tmp = 지점별매출리스트[:,0].argmin()
print(지점명[tmp])

A


In [119]:
지점별매출리스트[:,0].mean()
np.quantile(지점별매출리스트[:,0],(0.25))

1.75

In [123]:
aa = np.array([3,1,7,9])
print(np.sort(aa))
print(aa)
sort_idx = np.argsort(aa)
print(sort_idx)


[1 3 7 9]
[3 1 7 9]


array([1, 0, 2, 3], dtype=int64)

In [133]:
좌표리스트 = np.array([
    [1,5], # x,y
    [2,10],
    [3,6],
    [4,2],
    [5,3],
    [7,3]
])
구분 = np.array(['fail','fail','fail','pass','pass','pass'])

내좌표 = [5,5]
dists = 좌표리스트 - 내좌표
print("내좌표와 좌표들간 거리", dists)
dists = dists**2
print("거리를 각각 제곱",dists)
#내 좌표와 좌표리스트간 직선 거리
dists = np.sqrt(np.sum(dists, axis=1))
print("제곱들을 더해 제곱근(직선거리)",dists)
#직선거리를 정렬
sort_index = dists.argsort()
print("가장 가까이 배치되어야 할 순서 인덱스",sort_index)
print("정렬",dists[sort_index])
print(구분[sort_index])
print("결론: 나의 예측",구분[sort_index][0])

# 범위를 넓혀 가장 가까운 3개를 추출
print(구분[sort_index][:3])

내좌표와 좌표들간 거리 [[-4  0]
 [-3  5]
 [-2  1]
 [-1 -3]
 [ 0 -2]
 [ 2 -2]]
거리를 각각 제곱 [[16  0]
 [ 9 25]
 [ 4  1]
 [ 1  9]
 [ 0  4]
 [ 4  4]]
제곱들을 더해 제곱근(직선거리) [4.         5.83095189 2.23606798 3.16227766 2.         2.82842712]
가장 가까이 배치되어야 할 순서 인덱스 [4 2 5 3 0 1]
정렬 [2.         2.23606798 2.82842712 3.16227766 4.         5.83095189]
['pass' 'fail' 'pass' 'pass' 'fail' 'fail']
결론: 나의 예측 pass
['pass' 'fail' 'pass']


In [ ]:
# np.bincount(arr) -> "정수"데이터의 최대값까지의 빈도수 계산

In [134]:
arr4 = np.array([3,1,9,3])
np.bincount(arr4) # 0의 빈도수, 1의 빈도수, 2의 빈도수 ... 

array([0, 1, 0, 2, 0, 0, 0, 0, 0, 1], dtype=int64)

In [138]:
# np.unique(문자/정수배열, return_counts=True)

In [143]:
uql, uqc = np.unique(구분[sort_index][:3],return_counts=True)
print(uql,uqc)
print(uql[np.argmax(uqc)]) # 빈도수가 높은 글자

['fail' 'pass'] [1 2]
pass


In [144]:
[1,3,5][::-1]

[5, 3, 1]